### ISSUE TITLE
Nicer alert with icon?

### ISSUE THREAD

**Issue by tomtastic** [thisdougb/MagicPowerAlert#7]
It struck me that by switching to a dialog box, we could have a nice icon for the alert, and we can also set a time for it to automatically dismiss itself.

![image](https://user-images.githubusercontent.com/302127/148373671-9bb23ac6-aadb-4cbf-bb7b-77ce90103e92.png)
![image](https://user-images.githubusercontent.com/302127/148374418-102c1500-ff1b-4883-8b41-f0b094e5a981.png)

We can use the system icons for a Magic Mouse if relying on their absolute paths wasn't an issue?

**Comment by thisdougb** [comment]
ah @tomtastic sorry.  notifications haven't been working, so have just seen this.

**Comment by thisdougb** [comment]
@tomtastic yes, very cool.
