### ISSUE TITLE
Scheduling with cron fails unless granted FullDiskAccess

### ISSUE THREAD

**Issue by tomtastic** [thisdougb/MagicPowerAlert#9]
I noticed recently that no alerts were being generated from the crontab entry I had created.

I had to explicitly add `/usr/sbin/cron` to allow 'Full Disk Access' (FDA) in the Privacy tab of 'Security & Privacy' in System Preferences.
![](https://i.stack.imgur.com/e8KsI.png)
Whilst I can't see how to programatically add an item to the FDA list, we _can use this_ to see which apps are explicitly allowed FDA. So perhaps worth raising a warning notice to the user to enable it before they add a cron entry?
```
$ sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db \
>   'select client from access where auth_value and service = "kTCCServiceSystemPolicyAllFiles"'
/opt/X11/libexec/launchd_startx
/usr/libexec/sshd-keygen-wrapper
/usr/sbin/cron
/usr/sbin/smbd
com.googlecode.iterm2
com.objective-see.KnockKnock
com.objectiveSee.BlockBlock
com.sqwarq.DetectX-Swift
```

**Comment by tomtastic** [comment]
Might be nicer to abandon cron and just use `launchd` to setup a scheduled task.
For which I think ; 
* step 1 is symlinking the script into `/usr/local/bin/`, as launchd can be picky about paths it launches from.
* step 2 is writing a .plist similar to the below
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.thisdougb.magicpoweralert</string>
        <key>Program</key>
        <string>/usr/local/bin/MagicPowerAlert.sh</string>
        <key>StartInterval</key>
        <!-- Every 30mins = 60secs * 30 -->
        <integer>1800</integer>
    </dict>
</plist>
```
* step 3 is to load the plist
```
$ sudo launchctl load /Users/dougb/dev/MagicPowerAlert/MagicPowerAlert.plist
```

NB: Good reference material at : https://www.launchd.info/

**Comment by thisdougb** [comment]
I'm guessing the above method of using cron is different to cli cron, in terms of permissions required?
```
(py3.9) dougb $ crontab -l
*/30 * * * * /Users/dougb/dev/MagicPowerAlert/MagicPowerAlert.sh
```
I've thinking about adding AirPod Pro, or any connected device. Have you done any Swift coding?  Worth moving this to a Swift app, which would may make it easier to pick up any device, and do the installation/scheduling.

**Comment by tomtastic** [comment]
I haven't done any Swift yet sadly, the £99/yr developer subscription always seemed to stifle my enthusiasm for trying it out for small experiments and tools.

Perhaps my cron permissions issues were spurious, I'll close this for now.
